name: todoapi
version: 0.1.0.0
github: "gege251/servant-persistent-todoapi"
license: BSD3
author: "Szabo Gergely"
copyright: "2018 Szabo Gergely"

description: Please see the README on Github at <https://github.com/gege251/servant-persitent-todoapi#readme>

ghc-options: -Wall -fno-warn-orphans

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - todoapi
      - servant-client
      - warp
      - http-client
      - http-types

library:
  source-dirs:
    - src

executables:
  todoapi:
    main: Main.hs
    source-dirs: exe/TodoApi
    dependencies:
      - todoapi

  todoapi-gen-elm:
    main: Main.hs
    source-dirs: exe/GenerateElm
    dependencies:
      - todoapi

  todoapi-gen-docs:
    main: Main.hs
    source-dirs: exe/GenerateDocs
    dependencies:
      - todoapi

  todoapi-gen-swagger:
    main: Main.hs
    source-dirs: exe/GenerateSwagger
    dependencies:
      - todoapi

  todoapi-db-migrations:
    main: Main.hs
    source-dirs: exe/DBMigrations
    dependencies:
      - todoapi

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - DataKinds
  - ScopedTypeVariables
  - DuplicateRecordFields
  - QuasiQuotes
  - RankNTypes
  - FlexibleContexts
  - FlexibleInstances
  - TypeOperators
  - TypeFamilies

dependencies:
  - lens
  - protolude >= 0.2 && < 1
  - aeson
  - yaml
  - base
  - text
  - elm-bridge
  - servant
  - servant-server <= 0.13
  - servant-elm >= 0.6
  - servant-docs
  - servant-swagger
  - swagger2
  - transformers
  - aeson
  - wai
  - wai-cors
  - warp
  - postgresql-typed
  - monad-logger
  - uuid
