resolver: lts-11.1
packages:
  - "."
  - location:
      git: git@github.com:gege251/servant-elm
      commit: 75623d9aaa82e7095b45afbfef464d4224ee8f7a
    extra-dep: true
  - location:
      git: git@github.com:gege251/elm-export
      commit: fdee43cee30822836bdde1f231fdf1e909a68e80
    extra-dep: true
